
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tagpzwzxruxxxoldiwtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZ3B6d3p4cnV4eHhvbGRpd3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTYxODcsImV4cCI6MjA2MDA5MjE4N30.vyS_a_MAXGwzeUfvmoqMHOI0T5EtZaACoPwSSGbjq4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to handle errors from Supabase operations
export const handleSupabaseError = (error: any, defaultMessage = "An error occurred"): string => {
  console.error("Supabase operation error:", error);
  return error?.message || defaultMessage;
};
